### ISSUE TITLE
bcachefs fsck after upgrading to livetree never completes

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs-tools#113]
the title says it all ...
Tried with release code, debug code, -f, -v and --reconstruct-alloc, but in vain: after "going read-write", it  ends in an infinite loop.
The output of -f -v:
```
bch2_fs_open()                                                                                                                                       
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_read_super()                                                                                                                                    
bch2_read_super() ret 0                                                                                                                              
bch2_fs_alloc()                                                                                                                                      
bch2_fs_journal_init()                                                                                                                               
bch2_fs_journal_init() ret 0                                                                                                                         
bch2_fs_btree_cache_init()                                                                                                                           
bch2_fs_btree_cache_init() ret 0                                                                                                                     
bch2_fs_encryption_init()                                                                                                                            
bch2_fs_encryption_init() ret 0                                                                                                                      
__bch2_fs_compress_init()                                                                                                                            
__bch2_fs_compress_init() ret 0                                                                                                                      
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_dev_alloc()                                                                                                                                     
bch2_dev_alloc() ret 0                                                                                                                               
bch2_fs_alloc() ret 0                                                                                                                                
recovering from unclean shutdown                                                                                                                     
starting journal read                                                                                                                                
journal read done on device /dev/disk/by-id/scsi-2347466f10, ret 0                                                                                   
journal read done on device /dev/disk/by-partlabel/satavidm, ret 0                                                                                   
journal read done on device /dev/disk/by-partlabel/sataM2vi, ret 0                                                                                   
journal read done on device /dev/disk/by-partlabel/satavidm, ret 0                                                                                   
journal read done on device /dev/disk/by-partlabel/sasvidme, ret 0                                                                                   
journal read done on device /dev/disk/by-partlabel/nvmVideo, ret 0                                                                                   
journal read done on device /dev/disk/by-partlabel/satavide, ret 0                                                                                   
ja->sectors_free == ca->mi.bucket_size                                                                                                               
cur_idx 1/1286                                                                                                                                       
bucket_seq[0] = 0                                                                                                                                    
bucket_seq[1] = 143256                                                                                                                               
bucket_seq[2] = 0                                                                                                                                    
journal read done on device /dev/disk/by-partlabel/sasvidca, ret 0                                                                                   
journal read done, 1601518 keys in 413 entries, seq 628691                                                                                           
dropped unflushed entries 628688-628690                                                                                                              
starting alloc read                                                                                                                                  
alloc read done                                                                                                                                      
starting stripes_read                                                                                                                                
stripes_read done                                                                                                                                    
checking allocations                                                                                                                                 
bucket 5:10698 gen 1 data type user has wrong cached_sectors: got 512, should be 19, fixing                                                          
dev 1 has wrong buckets_unavailable: got 7926, should be 8726, fixing                                                                                
dev 1 has wrong btree buckets: got 7150, should be 7950, fixing                                                                                      
dev 1 has wrong btree sectors: got 3660800, should be 4070400, fixing                                                                                
dev 1 has wrong cached buckets: got 0, should be 87090, fixing                                                                                       
dev 1 has wrong cached sectors: got 0, should be 44590080, fixing                                                                                    
dev 2 has wrong buckets_unavailable: got 7859, should be 8661, fixing                                                                                
dev 2 has wrong btree buckets: got 7083, should be 7885, fixing                                                                                      
dev 2 has wrong btree sectors: got 3626496, should be 4037120, fixing                                                                                
dev 2 has wrong cached buckets: got 0, should be 87180, fixing                                                                                       
dev 2 has wrong cached sectors: got 0, should be 44636160, fixing                                                                                    
dev 3 has wrong buckets_unavailable: got 7604, should be 8416, fixing                                                                                
dev 3 has wrong btree buckets: got 6828, should be 7640, fixing                                                                                      
dev 3 has wrong btree sectors: got 3495936, should be 3911680, fixing                                                                                
dev 3 has wrong cached buckets: got 0, should be 87267, fixing                                                                                       
dev 3 has wrong cached sectors: got 0, should be 44680704, fixing                                                                                    
dev 4 has wrong buckets_unavailable: got 8033, should be 8836, fixing                                                                                
dev 4 has wrong btree buckets: got 7257, should be 8060, fixing                                                                                      
dev 4 has wrong btree sectors: got 3715584, should be 4126720, fixing                                                                                
dev 4 has wrong cached buckets: got 0, should be 87020, fixing                                                                                       
dev 4 has wrong cached sectors: got 0, should be 44554240, fixing                                                                                    
dev 5 has wrong cached buckets: got 0, should be 235168, fixing                                                                                      
dev 5 has wrong cached sectors: got 0, should be 120400840, fixing                                                                                   
dev 6 has wrong cached buckets: got 0, should be 148696, fixing                                                                                      
dev 6 has wrong cached sectors: got 0, should be 76129504, fixing                                                                                    
dev 7 has wrong buckets_unavailable: got 1299, should be 1302, fixing                                                                                
dev 7 has wrong btree buckets: got 0, should be 3, fixing                                                                                            
dev 7 has wrong btree sectors: got 0, should be 1536, fixing                                                                                         
dev 7 has wrong cached buckets: got 0, should be 160510, fixing                                                                                      
dev 7 has wrong cached sectors: got 0, should be 82178520, fixing                                                                                    
fs has wrong btree: got 14498816, should be 16147456, fixing                                                                                         
fs has wrong cached: got 0, should be 457170048, fixing                                                                                              
fs has wrong btree: 1/2 [1 2]: got 2226176, should be 2420736, fixing                                                                                
fs has wrong btree: 1/2 [2 4]: got 2367488, should be 2625536, fixing                                                                                
fs has wrong cached: 1/1 [4]: got 0, should be 44554240, fixing                                                                                      
fs has wrong btree: 1/2 [1 4]: got 2913280, should be 3274752, fixing                                                                                
fs has wrong cached: 1/1 [2]: got 0, should be 44636160, fixing                                                                                      
fs has wrong cached: 1/1 [6]: got 0, should be 76129504, fixing                                                                                      
fs has wrong btree: 1/2 [1 3]: got 2182144, should be 2445312, fixing                                                                                
fs has wrong btree: 1/2 [2 3]: got 2659328, should be 3027968, fixing                                                                                
fs has wrong btree: 1/2 [3 4]: got 2150400, should be 2350080, fixing                                                                                
fs has wrong btree: 1/2 [4 7]: got 0, should be 3072, fixing                                                                                         
fs has wrong cached: 1/1 [1]: got 0, should be 44590080, fixing                                                                                      
fs has wrong cached: 1/1 [3]: got 0, should be 44680704, fixing                                                                                      
fs has wrong cached: 1/1 [5]: got 0, should be 120400840, fixing                                                                                     
fs has wrong cached: 1/1 [7]: got 0, should be 82178520, fixing                                                                                      
done checking allocations                                                                                                                            
checking need_discard and freespace btrees                                                                                                           
done 
checking need_discard and freespace btrees                                                                                                      
starting journal replay, 1597161 keys                                                                                                                
going read-write
```

this is what gdb says:
```
(gdb) bt                                                                                                                                             
#0  0x00007f089c0deb8b in ?? () from /lib64/libc.so.6                                                                                                
#1  0x00007f089c0e519a in pthread_mutex_lock () from /lib64/libc.so.6                                                                                
#2  0x00005652cbff8a39 in raw_spin_lock (lock=0x7f089bfe5bb8) at include/linux/spinlock.h:20                                                         
#3  bch2_journal_pin_set (j=0x7f089bfe5908, seq=628259, pin=0x5652cca73f40, flush_fn=0x5652cbfca0c0 <bch2_btree_key_cache_journal_flush>)                at libbcachefs/journal_reclaim.c:380                                                                                                             
#4  0x00005652cbfcca78 in bch2_journal_pin_update (flush_fn=0x5652cbfca0c0 <bch2_btree_key_cache_journal_flush>, pin=<optimized out>,                    seq=<optimized out>, j=0x7f089bfe5908) at libbcachefs/journal_reclaim.h:66                                                                       
#5  bch2_btree_insert_key_cached (trans=trans@entry=0x7fffa462f760, path=<optimized out>, insert=<optimized out>)                                        at libbcachefs/btree_key_cache.c:550                                                                                                             
#6  0x00005652cbfec778 in do_btree_insert_one (i=0x5652cd26e200, trans=0x7fffa462f760) at libbcachefs/btree_update_leaf.c:410                        
#7  bch2_trans_commit_write_locked (trace_ip=<optimized out>, stopped_at=<synthetic pointer>, trans=0x7fffa462f760)                                      at libbcachefs/btree_update_leaf.c:744                                                                                                           
#8  do_bch2_trans_commit (trace_ip=<optimized out>, stopped_at=<synthetic pointer>, trans=0x7fffa462f760) at libbcachefs/btree_update_leaf.c:922     
#9  __bch2_trans_commit (trans=trans@entry=0x7fffa462f760) at libbcachefs/btree_update_leaf.c:1154                                                   
#10 0x00005652cbf6f056 in bch2_trans_commit (flags=<optimized out>, journal_seq=0x0, disk_res=0x0, trans=0x7fffa462f760)                                 at libbcachefs/btree_update.h:102                                                                                                                
#11 bch2_journal_replay (c=0x7f089bfc7000) at libbcachefs/recovery.c:563                                                                             
#12 bch2_fs_recovery (c=<optimized out>) at libbcachefs/recovery.c:1209                                                                              
#13 0x00005652cbfd5add in bch2_fs_start (c=c@entry=0x7f089bfc7000) at libbcachefs/super.c:897                                                        
#14 0x00005652cbfd7fef in bch2_fs_open (devices=devices@entry=0x7fffa462fdc8, nr_devices=nr_devices@entry=8, opts=...) at libbcachefs/super.c:1905   
#15 0x00005652cc014275 in cmd_fsck (argc=8, argc@entry=12, argv=0x7fffa462fdc8, argv@entry=0x7fffa462fda8) at cmd_fsck.c:90                          
#16 0x00005652cbf571ce in main (argc=<optimized out>, argv=0x7fffa462fda8) at bcachefs.c:197
```
*EDIT*: and the struct journal j from frame 3:
```
(gdb) print *j                                                                                                                                       
$2 = {flags = 6, reservations = {{counter = {counter = 18014398526259198}}, {v = 18014398526259198}, {cur_entry_offset = 1048574, idx = 3,                 unwritten_idx = 3, buf0_count = 0, buf1_count = 0, buf2_count = 0, buf3_count = 1}}, watermark = JOURNAL_WATERMARK_any,                          cur_entry_u64s = 7676, cur_entry_sectors = 512, cur_entry_error = JOURNAL_ERR_ok, prereserved = {{counter = {counter = 57997039341928448}}, {            v = 57997039341928448}, {waiting = 0, reserved = 0, remaining = 13503488}}, entry_u64s_reserved = 509, buf_size_want = 131072, buf = {{              data = 0x5652cc1c5000, {key = {_data = 0x7f089bfe5940, {{u64s = 0 '\000'}, {k = {u64s = 0 '\000', format = 0 '\000',                                           needs_whiteout = 0 '\000', type = 0 '\000', pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 0, offset = 0,                             inode = 0}}, v = {__nothing = 0x7f089bfe5968}}}}, key_pad = {0, 0, 0, 0}}, devs_written = {nr = 0 '\000',                                  devs = '\000' <repeats 15 times>}, wait = {list = {first = 0x0}}, last_seq = 0, expires = 0, flush_time = 0, buf_size = 65536, sectors = 0,        disk_sectors = 0, u64s_reserved = 509, noflush = false, must_flush = false, separate_flush = false}, {data = 0x5652cc1d6000, {key = {                    _data = 0x7f089bfe59e0, {{u64s = 0 '\000'}, {k = {u64s = 0 '\000', format = 0 '\000', needs_whiteout = 0 '\000', type = 0 '\000',                          pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 0, offset = 0, inode = 0}}, v = {__nothing = 0x7f089bfe5a08}}}},             key_pad = {0, 0, 0, 0}}, devs_written = {nr = 0 '\000', devs = '\000' <repeats 15 times>}, wait = {list = {first = 0x0}}, last_seq = 0,            expires = 0, flush_time = 0, buf_size = 65536, sectors = 0, disk_sectors = 0, u64s_reserved = 0, noflush = false, must_flush = false,                separate_flush = false}, {data = 0x5652cc1e7000, {key = {_data = 0x7f089bfe5a80, {{u64s = 0 '\000'}, {k = {u64s = 0 '\000',                                    format = 0 '\000', needs_whiteout = 0 '\000', type = 0 '\000', pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 0,                      offset = 0, inode = 0}}, v = {__nothing = 0x7f089bfe5aa8}}}}, key_pad = {0, 0, 0, 0}}, devs_written = {nr = 0 '\000',                      devs = '\000' <repeats 15 times>}, wait = {list = {first = 0x0}}, last_seq = 0, expires = 0, flush_time = 0, buf_size = 65536, sectors = 0,        disk_sectors = 0, u64s_reserved = 0, noflush = false, must_flush = false, separate_flush = false}, {data = 0x5652cc1f8000, {key = {                      _data = 0x7f089bfe5b20, {{u64s = 5 '\005'}, {k = {u64s = 5 '\005', format = 1 '\001', needs_whiteout = 0 '\000', type = 6 '\006',                          pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 0, offset = 0, inode = 0}}, v = {__nothing = 0x7f089bfe5b48}}}},             key_pad = {0, 0, 0, 0}}, devs_written = {nr = 0 '\000', devs = '\000' <repeats 15 times>}, wait = {list = {first = 0x0}},                          last_seq = 628257, expires = 208185073, flush_time = 0, buf_size = 65536, sectors = 128, disk_sectors = 512, u64s_reserved = 509,                    noflush = false, must_flush = false, separate_flush = false}}, lock = {lock = {__data = {__lock = 2, __count = 0, __owner = 30660,                     __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},                                                      __size = "\002\000\000\000\000\000\000\000\304w\000\000\001", '\000' <repeats 26 times>, __align = 2}}, blocked = 0, wait = {lock = {lock = {          __data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0,                            __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, task_list = {next = 0x7f089bfe5c10, prev = 0x7f089bfe5c10}},            async_wait = {list = {first = 0x0}}, preres_wait = {list = {first = 0x0}}, io = {{{wq = 0x0, s = 0x0, list = {next = 0x0}, fn = 0x0}, work = {             data = {counter = 0}, entry = {next = 0x0, prev = 0x0}, func = 0x0}}, parent = 0x0, remaining = {counter = 0}}, write_work = {work = {             data = {counter = 1}, entry = {next = 0x7f089bfe5c68, prev = 0x7f089bfe5c68}, func = 0x5652cbfc1770 <journal_write_work>}, timer = {                 expires = 208185073, function = 0x5652cc004b20 <delayed_work_timer_fn>, pending = false}, wq = 0x5652cc19af80}, seq = {counter = 628699},        seq_ondisk = 628698, flushed_seq_ondisk = 628698, last_seq_ondisk = 628257, err_seq = 0, last_empty_seq = 0, pin = {front = 628257,                    back = 628700, size = 32768, mask = 32767, data = 0x7f089bb5f000}, space = {{next_entry = 512, total = 964608}, {next_entry = 512,                     total = 964608}, {next_entry = 512, total = 964608}, {next_entry = 512, total = 965120}}, replay_journal_seq = 628259,                           replay_journal_seq_end = 628699, wp = {node = {next = 0x0, prev = 0x0}, lock = {lock = {__data = {__lock = 0, __count = 0, __owner = 0,                      __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>,                  __align = 0}}, last_used = 0, write_point = 0, data_type = BCH_DATA_none, sectors_free = 0, ptrs = {nr = 0, v = {0 <repeats 15 times>}},     
--Type <RET> for more, q to quit, c to continue without paging--
stripe = {next_alloc = {0 <repeats 64 times>}}}, err_lock = {lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0,           __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, reclaim_lock = {          lock = {__data = {__lock = 1, __count = 0, __owner = 30660, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0,                  __next = 0x0}}, __size = "\001\000\000\000\000\000\000\000\304w\000\000\001", '\000' <repeats 26 times>, __align = 1}}, reclaim_wait = {       lock = {lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0,                __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, task_list = {next = 0x7f089bfe6010, prev = 0x7f089bfe6010}},            reclaim_thread = 0x5652cc34fdd0, reclaim_kicked = false, next_reclaim = 208185113, nr_direct_reclaim = 0, nr_background_reclaim = 766,               last_flushed = 208184113, flush_in_progress = 0x5652cc39a940, flush_in_progress_dropped = false, pin_flush_wait = {lock = {lock = {__data = {                __lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},                __size = '\000' <repeats 39 times>, __align = 0}}, task_list = {next = 0x7f089bfe6088, prev = 0x7f089bfe6088}}, discard_lock = {lock = {           __data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},        __size = '\000' <repeats 39 times>, __align = 0}}, can_discard = false, last_flush_write = 208056827, res_get_blocked_start = 0,                 write_start_time = 0, nr_flush_writes = 0, nr_noflush_writes = 0, flush_write_time = 0x7f089bfe74b8, noflush_write_time = 0x7f089bfe7600,            blocked_time = 0x7f089bfe7890, flush_seq_time = 0x7f089bfe7748}
```

**Comment by koverstreet** [comment]
I suspect if you did a 'thr apply all bt', we would see another thread that's self deadlocking on the journal lock - I just pushed a fix for that.

Can you try again with the latest version? You'll probably hit another bug and see the journal getting stuck.

**Comment by jpsollie** [comment]
uhm .... I'm sorry to tell you, but your current code actually fixed the problem:
bcachefs fsck -y -f -v completed without any problem.
Here's the output of fsck:
```
bch2_fs_open()
bch2_read_super()
bch2_read_super() ret 0
bch2_read_super()
bch2_read_super() ret 0                                                                                                                              bch2_read_super()
bch2_read_super() ret 0                                                                                                                              bch2_read_super()
bch2_read_super() ret 0                                                                                                                              bch2_read_super()
bch2_read_super() ret 0                                                                                                                              bch2_read_super()
bch2_read_super() ret 0                                                                                                                              bch2_read_super()
bch2_read_super() ret 0                                                                                                                              bch2_read_super()
bch2_read_super() ret 0                                                                                                                              bch2_fs_alloc()
bch2_fs_journal_init()                                                                                                                               bch2_fs_journal_init() ret 0
bch2_fs_btree_cache_init()                                                                                                                           bch2_fs_btree_cache_init() ret 0
bch2_fs_encryption_init()
bch2_fs_encryption_init() ret 0
__bch2_fs_compress_init()                                                                                                                            __bch2_fs_compress_init() ret 0
bch2_dev_alloc()                                                                                                                                     bch2_dev_alloc() ret 0
bch2_dev_alloc()
bch2_dev_alloc() ret 0
bch2_dev_alloc()
bch2_dev_alloc() ret 0
bch2_dev_alloc()
bch2_dev_alloc() ret 0                                                                                                                               bch2_dev_alloc()
bch2_dev_alloc() ret 0                                                                                                                               bch2_dev_alloc()
bch2_dev_alloc() ret 0                                                                                                                               bch2_dev_alloc()
bch2_dev_alloc() ret 0                                                                                                                               bch2_dev_alloc()
bch2_dev_alloc() ret 0
bch2_fs_alloc() ret 0
recovering from clean shutdown, journal seq 628824
starting journal read
journal read done on device /dev/disk/by-id/scsi-2347466f10, ret 0
journal read done on device /dev/disk/by-partlabel/satavidm, ret 0
journal read done on device /dev/disk/by-partlabel/sataM2vi, ret 0
journal read done on device /dev/disk/by-partlabel/satavidm, ret 0
journal read done on device /dev/disk/by-partlabel/sasvidme, ret 0
journal read done on device /dev/disk/by-partlabel/nvmVideo, ret 0
journal read done on device /dev/disk/by-partlabel/satavide, ret 0
ja->sectors_free == ca->mi.bucket_size
cur_idx 1/1286
bucket_seq[0] = 0
bucket_seq[1] = 143256
bucket_seq[2] = 0
journal read done on device /dev/disk/by-partlabel/sasvidca, ret 0
journal read done, 0 keys in 1 entries, seq 628825
starting alloc read
alloc read done
starting stripes_read
stripes_read done
checking allocations
done checking allocations
checking need_discard and freespace btrees
done checking need_discard and freespace btrees
starting journal replay, 0 keys
journal replay done
reading snapshots table
reading snapshots done
starting fsck
checking extents
checking dirents
checking xattrs
checking root directory
checking inode nlinks
fsck done
ret 0
going read-write
mounted version=freespace opts=metadata_replicas=2,metadata_checksum=xxhash,data_checksum=xxhash,metadata_target=SSDM,foreground_target=SSDC,background_target=HDD,promote_target=SSDC,noinodes_use_key_cache,degraded,verbose,journal_reclaim_delay=1000,fsck,fix_errors,nojournal_transaction_names
bch2_fs_open() ret 0
shutting down
flushing journal and stopping allocators
flushing journal and stopping allocators complete
marking filesystem clean
shutdown complete
```
And here's the one of mount after fsck:
```
[551028.552621] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): recovering from clean shutdown, journal seq 628825
[551028.653474] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): ja->sectors_free == ca->mi.bucket_size 
[551028.653478] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): cur_idx 1/1286
[551028.653481] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[0] = 0
[551028.653483] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[1] = 143256
[551028.653485] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[2] = 0
[551028.735361] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): ja->sectors_free == ca->mi.bucket_size
[551028.735366] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): cur_idx 421/763
[551028.735368] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[420] = 0
[551028.735370] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[421] = 628821
[551028.735372] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[422] = 0
[551028.745472] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): ja->sectors_free == ca->mi.bucket_size
[551028.745477] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): cur_idx 405/763
[551028.745480] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[404] = 0
[551028.745482] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[405] = 628821
[551028.745484] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[406] = 0
[551074.508668] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): ja->sectors_free == ca->mi.bucket_size
[551074.508672] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): cur_idx 1/8192
[551074.508674] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[0] = 0
[551074.508676] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[1] = 141657
[551074.508678] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): bucket_seq[2] = 0
[551074.508720] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): journal read done, 0 keys in 1 entries, seq 628826
[551075.874924] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): checking allocations
[551121.408044] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): checking need_discard and freespace btrees
[551157.242481] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): starting fsck
[551165.417601] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): going read-write
[551165.440895] bcachefs (f7abb6e8-f27c-406e-bbde-645aa132d907): mounted version=freespace opts=metadata_replicas=2,metadata_checksum=xxhash,data_checksum=xxhash,metadata_target=SSDM,foreground_target=SSDC,background_target=HDD,promote_target=SSDC,noinodes_use_key_cache,journal_reclaim_delay=1000,fsck,fix_errors,nojournal_transaction_names
```
I'm sorry, I hoped I could help you trace it :(
If you want me to, I could create another bcachefs filesystem using older tools / kernel and try to recreate the situation?

**Comment by koverstreet** [comment]
It was probably one of the bugs I fixed today :)
