### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by mBornand** [koverstreet/bcachefs-tools#117]
Hello

I had to remove one drive of my array (because of a deffect), then I mounted the filesystem (-o degraded) and removed the drive from the filesystem. And i got an error while umounting it. now I cannot mount it And when running fsck it finds many "invalid journal entry dev usage: bad dev" then it says journal read done and dropped unflushed entries and then segfaults. 

kernel commit is d2e08891288
bcachefs-tools commit is 941075cb57

**Comment by koverstreet** [comment]
Can you run fsck under gdb and get a backtrace?
"thr apply all bt"

**Comment by mBornand** [comment]
Hello,

Under commit 986533d it segfaults in libbcachefs/replicas.c on line 975

Full backtrace:

```
Thread 13 (Thread 0x7ffff6f40600 (LWP 486) "btree_update"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x5555557d1e40) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x5555557d1ee0) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 12 (Thread 0x7ffff79eb600 (LWP 485) "bcachefs_io"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x55555577ce40) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x55555577cee0) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 11 (Thread 0x7ffff79f4600 (LWP 484) "bcachefs_copygc"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x55555577cb80) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x55555577cc10) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 10 (Thread 0x7ffff79fd600 (LWP 483) "bcachefs_btree_"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x55555577c880) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x55555577c940) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 9 (Thread 0x7ffff7a06600 (LWP 482) "bcachefs"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x55555577c600) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x55555577c670) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 8 (Thread 0x7ffff7a95600 (LWP 481) "timers"):
#0  0x00007ffff7b7b15a in __futex_abstimed_wait_common () from /usr/lib/libc.so.6
#1  0x00007ffff7b7d960 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libc.so.6
#2  0x000055555560d739 in timer_thread (arg=<optimized out>) at linux/timer.c:265
#3  0x0000555555613923 in kthread_start_fn (data=0x555555778770) at linux/kthread.c:25
#4  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#5  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7ffff7a9e600 (LWP 480) "aio_completion"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff7cfe277 in ?? () from /usr/lib/libaio.so.1
#2  0x0000555555611a64 in aio_completion_thread (arg=<optimized out>) at linux/blkdev.c:280
#3  0x0000555555613923 in kthread_start_fn (data=0x555555778150) at linux/kthread.c:25
#4  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#5  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7ffff7aa7600 (LWP 479) "events_freezabl"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x555555777e80) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x555555777f40) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7ffff7ab0600 (LWP 478) "events_unbound"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x555555777c00) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x555555777c70) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7ffff7ab9600 (LWP 477) "events_long"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x555555777900) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x5555557779a0) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7ffff7ac2600 (LWP 476) "events_highpri"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x555555777640) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x5555557776d0) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff7acb600 (LWP 475) "events"):
#0  0x00007ffff7bfca9d in syscall () from /usr/lib/libc.so.6
#1  0x000055555560e0a1 in futex (val3=0, uaddr2=0x0, timeout=0x0, val=<optimized out>, op=128, uaddr=<optimized out>) at /usr/include/urcu/futex.h:72
#2  schedule () at linux/sched.c:41
#3  0x000055555560e2fe in worker_thread (arg=0x555555777340) at linux/workqueue.c:252
#4  0x0000555555613923 in kthread_start_fn (data=0x555555777400) at linux/kthread.c:25
#5  0x00007ffff7b7e5c2 in start_thread () from /usr/lib/libc.so.6
#6  0x00007ffff7c03584 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7accb80 (LWP 471) "bcachefs"):
#0  0x00005555555d9890 in bch2_have_enough_devs (c=c@entry=0x7ffff7a08000, devs=..., flags=flags@entry=12, print=print@entry=false) at libbcachefs/replicas.c:975
#1  0x00005555555b29ca in bch2_write_super (c=c@entry=0x7ffff7a08000) at libbcachefs/super-io.c:901
#2  0x0000555555560613 in bch2_journal_seq_blacklist_add (c=c@entry=0x7ffff7a08000, start=6258397, end=6258408) at libbcachefs/journal_seq_blacklist.c:115
#3  0x00005555555eb1ea in bch2_fs_recovery (c=0x7ffff7a08000) at libbcachefs/recovery.c:1178
#4  0x000055555558537d in bch2_fs_start (c=c@entry=0x7ffff7a08000) at libbcachefs/super.c:896
#5  0x00005555555877c1 in bch2_fs_open (devices=devices@entry=0x7fffffffeb30, nr_devices=<optimized out>, nr_devices@entry=2, opts=...) at libbcachefs/super.c:1897
#6  0x0000555555608cf5 in cmd_fsck (argc=2, argc@entry=3, argv=0x7fffffffeb30, argv@entry=0x7fffffffeb28) at cmd_fsck.c:90
#7  0x000055555555e196 in main (argc=<optimized out>, argv=0x7fffffffeb28) at bcachefs.c:197
```

If you need more info I could run more tests.

**Comment by mBornand** [comment]
If I now try to mount it, I get the same error but in the kernel.

**Comment by koverstreet** [comment]
Thanks, it looks like we didn't delete replicas entries referring to the device you deleted, which makes sense as we already know we didn't delete all keys that refer to that device.

I'll work on reproducing the issue and writing some tests - I'll have to write some new repair code for this.

**Comment by koverstreet** [comment]
Can you run bcachefs show-super -f all and get me the output?

**Comment by mBornand** [comment]
[super-nvme.txt](https://github.com/koverstreet/bcachefs-tools/files/8457600/super-nvme.txt)
[super-sda.txt](https://github.com/koverstreet/bcachefs-tools/files/8457601/super-sda.txt)

Here are the files, but I tried earlier to force the fsck, it may have changed things, but I still get a segfault.

**Comment by koverstreet** [comment]
Which was the device you removed?

**Comment by mBornand** [comment]
I had two hdd as background one of them. What do you need UUID or something else?

I just checked gdb gives me still the same backtrace.

**Comment by mBornand** [comment]
If I correctly remember:

0. Is the hdd still present
1. Is the hdd evacuated and removed(with failure)
2. Is the ssd still present

**Comment by koverstreet** [comment]
Can you get me the output of
bcachefs show-super -f all
As well as the full output when you run fsck?
I've reproduced an issue with a pointer in a btree node key not getting removed in the device removal path, which fits with your bug. What I'm not sure about yet is why we're finding the invalid device when writing the superblock, not reading it - I need to see  what fsck is doing.

**Comment by mBornand** [comment]
I already gave you the show-super I had, but I think I corrupted the disk afterwards by trying to repair it and forgot to back it up, so I reused them for a new filesystem.

There was really nothing else than the standard fsck output, a bunch of bad dev error as mentioned in the first comment and the segfault after "going read-write".
