### ISSUE TITLE
bcachefs-tools subvolume delete in wildcard failed

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs-tools#244]
ls 
1708763445  1708763449  1708763452

/usr/local/sbin/bcachefs subvolume delete  ./*
error: unexpected argument './1708763449' found

Usage: subvolume delete <TARGET>

For more information, try '--help'.

Lists=`ls`
for List in $Lists
do
/usr/local/sbin/bcachefs subvolume delete ./{$List}
echo /usr/local/sbin/bcachefs subvolume delete ./$List
done

```
thread 'main' panicked at src/commands/cmd_subvolume.rs:55:45:
Failed to delete the subvolume: Errno { code: 2, description: Some("No such file or directory") }
stack backtrace:
   0:     0x5650c4023986 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5650c4023986 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5650c4023986 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5650c4023986 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5650c4043840 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x5650c4043840 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x5650c40219bf - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x5650c4023764 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5650c4023764 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5650c4024cc7 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x5650c4024a29 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x5650c4025158 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x5650c4025032 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x5650c4023e86 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5650c4024d90 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x5650c3e57bf5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x5650c3e58063 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x5650c3e84e06 - bcachefs::commands::cmd_subvolume::cmd_subvolumes::hf826aaf6539b1df7
  18:     0x5650c3e70882 - bcachefs::main::h829b71d6a5413e42
  19:     0x5650c3e81903 - std::sys_common::backtrace::__rust_begin_short_backtrace::he1fe0e976ed4f886
  20:     0x5650c3e7e4f9 - std::rt::lang_start::{{closure}}::hf12a3925ad974540
  21:     0x5650c401b791 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  22:     0x5650c401b791 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  23:     0x5650c401b791 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  24:     0x5650c401b791 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  25:     0x5650c401b791 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  26:     0x5650c401b791 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  27:     0x5650c401b791 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  28:     0x5650c401b791 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  29:     0x5650c401b791 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  30:     0x5650c3e70cc5 - main
  31:     0x7fe641229d90 - <unknown>
  32:     0x7fe641229e40 - __libc_start_main
  33:     0x5650c3e59845 - _start
  34:                0x0 - <unknown>
/usr/local/sbin/bcachefs subvolume delete ./170876345
```

bcachefs-tool version 16661be29497ce4940039fe49e3ebb71f72a2052

**Comment by Komzpa** [comment]
Current `bcachefs-tools` master appears to cover this old report.

The wildcard case originally failed because `subvolume delete` accepted only one target; current `src/commands/subvolume.rs` has `Delete { targets: Vec<PathBuf> }` and iterates over every target. That came from commit `cb8dc1b2baf8e79ad3cf035dce964297bf16ddde` (`Allow multiple targets for subvolume delete.`), which is on current master.

Current master also marks create/delete targets as required via `3bfe433d22b4f1800f45e459defbad9b477e1af6` (`bcachefs-tools: make targets of subvolume create/delete required`). The delete path now returns contextual errors (`subvolume path does not exist or can not be canonicalized`, `Failed to delete the subvolume`) instead of the old `unwrap`/panic-style failure shown here.

So I would treat the reported wildcard/multiple-target failure and panic as stale-covered by current master. If a current build still fails, it would help to have the exact command and current `bcachefs version`.

**Comment by bhzhu203** [comment]
> Current `bcachefs-tools` master appears to cover this old report.
> 
> The wildcard case originally failed because `subvolume delete` accepted only one target; current `src/commands/subvolume.rs` has `Delete { targets: Vec<PathBuf> }` and iterates over every target. That came from commit `cb8dc1b2baf8e79ad3cf035dce964297bf16ddde` (`Allow multiple targets for subvolume delete.`), which is on current master.
> 
> Current master also marks create/delete targets as required via `3bfe433d22b4f1800f45e459defbad9b477e1af6` (`bcachefs-tools: make targets of subvolume create/delete required`). The delete path now returns contextual errors (`subvolume path does not exist or can not be canonicalized`, `Failed to delete the subvolume`) instead of the old `unwrap`/panic-style failure shown here.
> 
> So I would treat the reported wildcard/multiple-target failure and panic as stale-covered by current master. If a current build still fails, it would help to have the exact command and current `bcachefs version`.

Yes it is solved .
