### ISSUE TITLE
bcachefs fsck could not write journal error

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs-tools#41]
related to https://github.com/koverstreet/bcachefs/issues/189
I'll post necessary info here to help finding the problem in userspace.
GDB backtrace for Error in recovery: journal replay failed:
```
(gdb) bt
#0  bch2_journal_write (cl=0x7ffff7ac6008) at libbcachefs/journal_io.c:1503
#1  0x0000555555562cc5 in worker_thread (arg=0x555555774800) at linux/workqueue.c:262
#2  0x000055555555f1f9 in kthread_start_fn (data=0x5555557748a0) at linux/kthread.c:25
#3  0x00007ffff7cc2fde in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff7c0573f in clone () from /lib64/libc.so.6
```
Some variables which *might* be useful for debugging:
```
(gdb) print ret
$1 = -30
(gdb) print *j
$3 = {flags = 55, reservations = {{counter = {counter = 29360814}}, {v = 29360814}, {cur_entry_offset = 686, idx = 0, unwritten_idx = 3, buf0_count = 1, buf1_count = 0, buf2_count = 0, buf3_count = 0}}, cur_entry_u64s = 130745, 
  cur_entry_sectors = 1024, cur_entry_error = cur_entry_ok, prereserved = {{counter = {counter = 56998682783911060}}, {v = 56998682783911060}, {reserved = 3220, remaining = 13271040}}, entry_u64s_reserved = 320, 
  buf_size_want = 2097152, buf = {{data = 0x7ffe8848f000, {key = {_data = 0x7ffff7ac4e20, {{u64s = 5 '\005'}, {k = {u64s = 5 '\005', format = 1 '\001', needs_whiteout = 0 '\000', type = 6 '\006', pad = "", version = {lo = 0, hi = 0}, 
                size = 0, p = {snapshot = 0, offset = 0, inode = 0}}, v = {__nothing = 0x7ffff7ac4e48}}}}, key_pad = {1125899910053889, 0, 0, 0}}, wait = {list = {first = 0x0}}, buf_size = 1048576, sectors = 2048, 
      disk_sectors = 4294965760, u64s_reserved = 320, noflush = false, must_flush = false, separate_flush = false, has_inode = {0 <repeats 67 times>, 68719476736, 0 <repeats 60 times>}}, {data = 0x7ffe88590000, {key = {
          _data = 0x7ffff7ac5290, {{u64s = 6 '\006'}, {k = {u64s = 6 '\006', format = 1 '\001', needs_whiteout = 0 '\000', type = 6 '\006', pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 0, offset = 0, inode = 0}}, 
              v = {__nothing = 0x7ffff7ac52b8}}}}, key_pad = {1125899910037505, 0, 0, 0}}, wait = {list = {first = 0x0}}, buf_size = 1048576, sectors = 0, disk_sectors = 4294966784, u64s_reserved = 320, noflush = false, 
      must_flush = false, separate_flush = true, has_inode = {1, 0 <repeats 66 times>, 68719476736, 0 <repeats 29 times>, 1125899906842624, 0 <repeats 30 times>}}, {data = 0x7ffe88691000, {key = {_data = 0x7ffff7ac5700, {{
              u64s = 6 '\006'}, {k = {u64s = 6 '\006', format = 1 '\001', needs_whiteout = 0 '\000', type = 6 '\006', pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 0, offset = 0, inode = 0}}, v = {
                __nothing = 0x7ffff7ac5728}}}}, key_pad = {1125899910021121, 0, 0, 0}}, wait = {list = {first = 0x0}}, buf_size = 1048576, sectors = 0, disk_sectors = 4294966784, u64s_reserved = 320, noflush = false, 
      must_flush = false, separate_flush = true, has_inode = {1, 0 <repeats 47 times>, 144115188075855872, 0 <repeats 18 times>, 68719476736, 0 <repeats 60 times>}}, {data = 0x7ffe88792000, {key = {_data = 0x7ffff7ac5b70, {{
              u64s = 5 '\005'}, {k = {u64s = 5 '\005', format = 1 '\001', needs_whiteout = 0 '\000', type = 6 '\006', pad = "", version = {lo = 0, hi = 0}, size = 0, p = {snapshot = 0, offset = 0, inode = 0}}, v = {
                __nothing = 0x7ffff7ac5b98}}}}, key_pad = {1125899910070273, 0, 0, 0}}, wait = {list = {first = 0x0}}, buf_size = 2097152, sectors = 0, disk_sectors = 4294966784, u64s_reserved = 320, noflush = false, 
      must_flush = false, separate_flush = false, has_inode = {1, 0 <repeats 17 times>, 8796093022208, 0 <repeats 48 times>, 68719476736, 0 <repeats 60 times>}}}, lock = {count = 0}, blocked = 0, wait = {lock = {count = 0}, 
    task_list = {next = 0x7ffff7ac5fe8, prev = 0x7ffff7ac5fe8}}, async_wait = {list = {first = 0x0}}, preres_wait = {list = {first = 0x0}}, io = {{{wq = 0x0, s = 0x7ffff7ac6010, list = {next = 0x7ffff7ac6010}, 
        fn = 0x55555560d730 <bch2_journal_write>}, work = {data = {counter = 0}, entry = {next = 0x7ffff7ac6010, prev = 0x7ffff7ac6010}, func = 0x55555560d730 <bch2_journal_write>}}, parent = 0x0, remaining = {counter = -2147483647}}, 
  write_work = {work = {data = {counter = 1}, entry = {next = 0x7ffff7ac6040, prev = 0x7ffff7ac6040}, func = 0x5555555cda30 <journal_write_work>}, timer = {expires = 24338323, function = 0x555555562e00 <delayed_work_timer_fn>, 
      pending = true}, wq = 0x555555775040}, seq = {counter = 1484028}, seq_ondisk = 1484026, flushed_seq_ondisk = 1484026, last_seq_ondisk = 1483417, err_seq = 0, last_empty_seq = 0, pin = {front = 1483419, back = 1484029, 
    size = 32768, mask = 32767, data = 0x7ffff789e000}, space = {{next_entry = 1024, total = 543744}, {next_entry = 1024, total = 543744}, {next_entry = 1024, total = 545792}, {next_entry = 1024, total = 1048576}}, 
  replay_journal_seq = 0, replay_journal_seq_end = 1483984, wp = {node = {next = 0x0, prev = 0x0}, lock = {lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {
            __prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, last_used = 0, write_point = 0, type = BCH_DATA_none, sectors_free = 0, ptrs = {nr = 0, v = {0 <repeats 15 times>}}, stripe = {next_alloc = {
        1251336411, 54533930, 812405510, 3326604933, 14468065, 0 <repeats 59 times>}}}, err_lock = {count = 0}, reclaim_lock = {lock = {__data = {__lock = 2, __count = 0, __owner = 7978, __nusers = 1, __kind = 0, __spins = 0, 
        __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = "\002\000\000\000\000\000\000\000*\037\000\000\001", '\000' <repeats 26 times>, __align = 2}}, reclaim_thread = 0x555555929860, reclaim_kicked = true, 
  nr_direct_reclaim = 0, nr_background_reclaim = 0, last_flushed = 24337325, flush_in_progress = 0x55568bb17210, pin_flush_wait = {lock = {count = 0}, task_list = {next = 0x7ffff7ac63d8, prev = 0x7ffff7ac63d8}}, discard_lock = {
    lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, can_discard = false, 
  write_delay_ms = 1000, reclaim_delay_ms = 100, last_flush_write = 24337323, res_get_blocked_start = 0, need_write_time = 24337323522917, write_start_time = 24337323914735, nr_flush_writes = 44, nr_noflush_writes = 0, 
  write_time = 0x7ffff7ac7190, delay_time = 0x7ffff7ac72b8, blocked_time = 0x7ffff7ac7508, flush_seq_time = 0x7ffff7ac73e0}
(gdb) print *cl
$4 = {{{wq = 0x0, s = 0x7ffff7ac6010, list = {next = 0x7ffff7ac6010}, fn = 0x55555560d730 <bch2_journal_write>}, work = {data = {counter = 0}, entry = {next = 0x7ffff7ac6010, prev = 0x7ffff7ac6010}, 
      func = 0x55555560d730 <bch2_journal_write>}}, parent = 0x0, remaining = {counter = -2147483647}}
(gdb) print *end
$8 = {u64s = 0, btree_id = 0 '\000', level = 0 '\000', type = 0 '\000', pad = "\000\000", {start = 0x7ffe88891e58, _data = 0x7ffe88891e58}}
(gdb) print sectors
$9 = 1756
(gdb) print nr_rw_members
$11 = 0
```
That's it for now ... I hope I can gather more info soon :)

**Comment by jpsollie** [comment]
bt for "unable to write journal to sufficient devices:"
```
(gdb) bt
#0  journal_write_done (cl=0x7ffff7ac6008) at libbcachefs/journal_io.c:1254
#1  0x0000555555562cc5 in worker_thread (arg=0x555555774800) at linux/workqueue.c:262
#2  0x000055555555f1f9 in kthread_start_fn (data=0x5555557748a0) at linux/kthread.c:25
#3  0x00007ffff7cc2fde in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff7c0573f in clone () from /lib64/libc.so.6
```
Var info (this time pretty printed to keep the headache off @koverstreet ):
```
(gdb) print *j
$1 = {
  flags = 55,
  reservations = {
    {
      counter = {
        counter = 30408703
      }
    },
    {
      v = 30408703
    },
    {
      cur_entry_offset = 1048575,
      idx = 0,
      unwritten_idx = 3,
      buf0_count = 1,
      buf1_count = 0,
      buf2_count = 0,
      buf3_count = 0
    }
  },
  cur_entry_u64s = 130745,
  cur_entry_sectors = 1024,
  cur_entry_error = cur_entry_ok,
  prereserved = {
    {
      counter = {
        counter = 57280157760621750
      }
    },
    {
      v = 57280157760621750
    },
    {
      reserved = 3254,
      remaining = 13336576
    }
  },
  entry_u64s_reserved = 320,
  buf_size_want = 2097152,
  buf = {{
      data = 0x7ffe8848f000,
      {
        key = {
          _data = 0x7ffff7ac4e20,
          {
            {
              u64s = 5 '\005'
            },
            {
              k = {
                u64s = 5 '\005',
                format = 1 '\001',
                needs_whiteout = 0 '\000',
                type = 6 '\006',
                pad = "",
                version = {
                  lo = 0,
                  hi = 0
                },
                size = 0,
                p = {
                  snapshot = 0,
                  offset = 0,
                  inode = 0
                }
              },
              v = {
                __nothing = 0x7ffff7ac4e48
              }
            }
          }
        },
        key_pad = {1125899909464065, 0, 0, 0}
      },
      wait = {
        list = {
          first = 0x0
        }
      },
      buf_size = 1048576,
      sectors = 2048,
      disk_sectors = 4294965760,
      u64s_reserved = 320,
      noflush = false,
      must_flush = false,
      separate_flush = false,
      has_inode = {0 <repeats 67 times>, 68719476736, 0 <repeats 60 times>}
    }, {
      data = 0x7ffe88590000,
      {
        key = {
          _data = 0x7ffff7ac5290,
          {
            {
              u64s = 6 '\006'
            },
            {
              k = {
                u64s = 6 '\006',
                format = 1 '\001',
                needs_whiteout = 0 '\000',
                type = 6 '\006',
                pad = "",
                version = {
                  lo = 0,
                  hi = 0
                },
                size = 0,
                p = {
                  snapshot = 0,
                  offset = 0,
                  inode = 0
                }
              },
              v = {
                __nothing = 0x7ffff7ac52b8
              }
            }
          }
        },
        key_pad = {1125899909447681, 0, 0, 0}
      },
      wait = {
        list = {
          first = 0x0
        }
      },
      buf_size = 1048576,
      sectors = 0,
      disk_sectors = 4294966784,
      u64s_reserved = 320,
      noflush = false,
      must_flush = false,
      separate_flush = true,
      has_inode = {0 <repeats 48 times>, 144115188075855872, 0 <repeats 18 times>, 68719476736, 0 <repeats 29 times>, 1125899906842624, 0 <repeats 30 times>}
    }, {
      data = 0x7ffe88691000,
      {
        key = {
          _data = 0x7ffff7ac5700,
          {
            {
              u64s = 6 '\006'
            },
            {
              k = {
                u64s = 6 '\006',
                format = 1 '\001',
                needs_whiteout = 0 '\000',
                type = 6 '\006',
                pad = "",
                version = {
                  lo = 0,
                  hi = 0
                },
                size = 0,
                p = {
                  snapshot = 0,
                  offset = 0,
                  inode = 0
                }
              },
              v = {
                __nothing = 0x7ffff7ac5728
              }
            }
          }
        },
        key_pad = {1125899909431297, 0, 0, 0}
      },
      wait = {
        list = {
          first = 0x0
        }
      },
      buf_size = 1048576,
      sectors = 0,
      disk_sectors = 4294966784,
      u64s_reserved = 320,
      noflush = false,
      must_flush = false,
      separate_flush = true,
      has_inode = {1, 0 <repeats 47 times>, 144115188075855872, 0 <repeats 18 times>, 68719476736, 0 <repeats 60 times>}
    }, {
      data = 0x7ffe88792000,
      {
        key = {
          _data = 0x7ffff7ac5b70,
          {
            {
              u64s = 5 '\005'
            },
            {
              k = {
                u64s = 5 '\005',
                format = 1 '\001',
                needs_whiteout = 0 '\000',
                type = 6 '\006',
                pad = "",
                version = {
                  lo = 0,
                  hi = 0
                },
                size = 0,
                p = {
                  snapshot = 0,
                  offset = 0,
                  inode = 0
                }
              },
              v = {
                __nothing = 0x7ffff7ac5b98
              }
            }
          }
        },
        key_pad = {1125899909480449, 0, 0, 0}
      },
      wait = {
        list = {
          first = 0x0
        }
      },
      buf_size = 2097152,
      sectors = 0,
      disk_sectors = 4294966784,
      u64s_reserved = 320,
      noflush = false,
      must_flush = false,
      separate_flush = false,
      has_inode = {1, 0 <repeats 17 times>, 8796093022208, 0 <repeats 48 times>, 68719476736, 0 <repeats 29 times>, 1125899906842624, 0 <repeats 30 times>}
    }},
  lock = {
    count = 0
  },
  blocked = 0,
  wait = {
    lock = {
      count = 0
    },
    task_list = {
      next = 0x7ffff7ac5fe8,
      prev = 0x7ffff7ac5fe8
    }
  },
  async_wait = {
    list = {
      first = 0x0
    }
  },
  preres_wait = {
    list = {
      first = 0x0
    }
  },
  io = {
    {
      {
        wq = 0x0,
        s = 0x7ffff7ac6010,
        list = {
          next = 0x7ffff7ac6010
        },
        fn = 0x55555560e800 <journal_write_done>
      },
      work = {
        data = {
          counter = 0
        },
        entry = {
          next = 0x7ffff7ac6010,
          prev = 0x7ffff7ac6010
        },
        func = 0x55555560e800 <journal_write_done>
      }
    },
    parent = 0x0,
    remaining = {
      counter = -2147483647
    }
  },
  write_work = {
    work = {
      data = {
        counter = 1
      },
      entry = {
        next = 0x7ffff7ac6040,
        prev = 0x7ffff7ac6040
      },
      func = 0x5555555cda30 <journal_write_work>
    },
    timer = {
      expires = 25734666,
      function = 0x555555562e00 <delayed_work_timer_fn>,
      pending = true
    },
    wq = 0x555555775040
  },
  seq = {
    counter = 1484084
  },
  seq_ondisk = 1484082,
  flushed_seq_ondisk = 1484082,
  last_seq_ondisk = 1483455,
  err_seq = 1484084,
  last_empty_seq = 0,
  pin = {
    front = 1483457,
    back = 1484085,
    size = 32768,
    mask = 32767,
    data = 0x7ffff789e000
  },
  space = {{
      next_entry = 1024,
      total = 545792
    }, {
      next_entry = 1024,
      total = 545792
    }, {
      next_entry = 1024,
      total = 547840
    }, {
      next_entry = 1024,
      total = 1048576
    }},
  replay_journal_seq = 0,
  replay_journal_seq_end = 1484035,
  wp = {
    node = {
      next = 0x0,
      prev = 0x0
    },
    lock = {
      lock = {
        __data = {
          __lock = 0,
          __count = 0,
          __owner = 0,
          __nusers = 0,
          __kind = 0,
          __spins = 0,
          __elision = 0,
          __list = {
            __prev = 0x0,
            __next = 0x0
          }
        },
        __size = '\000' <repeats 39 times>,
        __align = 0
      }
    },
    last_used = 0,
    write_point = 0,
    type = BCH_DATA_none,
    sectors_free = 0,
    ptrs = {
      nr = 0,
      v = {0 <repeats 15 times>}
    },
    stripe = {
      next_alloc = {1233224357, 36505969, 794306381, 3308533152, 14470036, 0 <repeats 59 times>}
    }
  },
  err_lock = {
    count = 0
  },
  reclaim_lock = {
    lock = {
      __data = {
        __lock = 2,
        __count = 0,
        __owner = 8145,
        __nusers = 1,
        __kind = 0,
        __spins = 0,
        __elision = 0,
        __list = {
          __prev = 0x0,
          __next = 0x0
        }
      },
      __size = "\002\000\000\000\000\000\000\000\321\037\000\000\001", '\000' <repeats 26 times>,
      __align = 2
    }
  },
  reclaim_thread = 0x55555592bc60,
  reclaim_kicked = true,
  nr_direct_reclaim = 0,
  nr_background_reclaim = 0,
  last_flushed = 25733669,
  flush_in_progress = 0x55568c6b4b90,
  pin_flush_wait = {
    lock = {
      count = 0
    },
    task_list = {
      next = 0x7ffff7ac63d8,
      prev = 0x7ffff7ac63d8
    }
  },
  discard_lock = {
    lock = {
      __data = {
        __lock = 0,
        __count = 0,
        __owner = 0,
        __nusers = 0,
        __kind = 0,
        __spins = 0,
        __elision = 0,
        __list = {
          __prev = 0x0,
          __next = 0x0
        }
      },
      __size = '\000' <repeats 39 times>,
      __align = 0
    }
  },
  can_discard = false,
  write_delay_ms = 1000,
  reclaim_delay_ms = 100,
  last_flush_write = 25733667,
  res_get_blocked_start = 0,
  need_write_time = 25733666904770,
  write_start_time = 25733667287871,
  nr_flush_writes = 49,
  nr_noflush_writes = 0,
  write_time = 0x7ffff7ac7190,
  delay_time = 0x7ffff7ac72b8,
  blocked_time = 0x7ffff7ac7508,
  flush_seq_time = 0x7ffff7ac73e0
}
(gdb) print *w
$2 = {
  data = 0x7ffe88792000,
  {
    key = {
      _data = 0x7ffff7ac5b70,
      {
        {
          u64s = 5 '\005'
        },
        {
          k = {
            u64s = 5 '\005',
            format = 1 '\001',
            needs_whiteout = 0 '\000',
            type = 6 '\006',
            pad = "",
            version = {
              lo = 0,
              hi = 0
            },
            size = 0,
            p = {
              snapshot = 0,
              offset = 0,
              inode = 0
            }
          },
          v = {
            __nothing = 0x7ffff7ac5b98
          }
        }
      }
    },
    key_pad = {1125899909480449, 0, 0, 0}
  },
  wait = {
    list = {
      first = 0x0
    }
  },
  buf_size = 2097152,
  sectors = 0,
  disk_sectors = 4294966784,
  u64s_reserved = 320,
  noflush = false,
  must_flush = false,
  separate_flush = false,
  has_inode = {1, 0 <repeats 17 times>, 8796093022208, 0 <repeats 48 times>, 68719476736, 0 <repeats 29 times>, 1125899906842624, 0 <repeats 30 times>}
}
(gdb) print devs
$3 = {
  nr = 0 '\000',
  devs = {<optimized out> <repeats 16 times>}
}
```
And that's all I got for this backtrace
```

**Comment by jpsollie** [comment]
Another one, not that useful but it shows where the program actually fails.
When using fsck -n:
```
fsck -v -n /dev/nvme0n1p6 /dev/sdi1 /dev/sdj2 /dev/sdb4 /dev/disk/by-id/scsi-2b3e68cf400d00000
journal read done, 4690346 keys in 580 entries, seq 1484083
starting alloc read
alloc read done
starting stripes_read
stripes_read done
starting mark and sweep
mark and sweep done
starting journal replay
Unable to allocate journal write
emergency read only
unable to write journal to sufficient devices
Error in recovery: journal replay failed (-5)
shutting down
flushing journal and stopping allocators
flushing journal and stopping allocators complete
shutdown complete
bcachefs: bch2_fs_open() ret -5
error opening /dev/nvme0n1p6: Input/output error
```
I verified whether nvme0n1p6 was still ok:
```
dd if=/dev/nvme0n1p6 of=/dev/null bs=4096 count=100
100+0 records in
100+0 records out
409600 bytes (410 kB, 400 KiB) copied, 0.0405125 s, 10.1 MB/s
```

**Comment by jpsollie** [comment]
Closing ticket - reformatted filesystem
