### ISSUE TITLE
segmention fault while format disks

### ISSUE THREAD

**Issue by colttt** [koverstreet/bcachefs-tools#58]
Hello, 
I try to run the following command, but I got an (not very usefull) error:

```
bcachefs format --group=ssd_read /dev/disk/by-id/dm-name-mpathb --group=ssd_write /dev/disk/by-id/dm-name-mpatha /dev/disk/by-id/dm-name-mpathm --group hdd=/dev/disk/by-id/dm-name-mpathc /dev/disk/by-id/dm-name-mpathd /dev/disk/by-id/dm-name-mpathe /dev/disk/by-id/dm-name-mpathf /dev/disk/by-id/dm-name-mpathg /dev/disk/by-id/dm-name-mpathh /dev/disk/by-id/dm-name-mpathi /dev/disk/by-id/dm-name-mpathj /dev/disk/by-id/dm-name-mpathk /dev/disk/by-id/dm-name-mpathl /dev/disk/by-id/dm-name-mpathn /dev/disk/by-id/dm-name-mpatho /dev/disk/by-id/dm-name-mpathp /dev/disk/by-id/dm-name-mpathq /dev/disk/by-id/dm-name-mpathr /dev/disk/by-id/dm-name-mpaths /dev/disk/by-id/dm-name-mpatht /dev/disk/by-id/dm-name-mpathu --replicas=2 --foreground_target=ssd_write --promote_target=ssd_read --background_target=hdd
Segmentation fault
```

**Comment by colttt** [comment]
from ` --group hdd=`
to  `--group=hdd`

**Comment by koverstreet** [comment]
I can't repro it, but I'd like to fix this - can you run your original
command under gdb and give me the backtrace?

**Comment by colttt** [comment]
It was my fault. I used `--group hdd=` instead of `--group=hdd`

**Comment by koverstreet** [comment]
But we should never segfault just because of an invalid argument

**Comment by colttt** [comment]
OK, i hope that is what you need:

```
gdb
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) 
(gdb) 
(gdb) file /usr/local/sbin/bcachefs
Reading symbols from /usr/local/sbin/bcachefs...done.
(gdb) run format --group=ssd_read /dev/disk/by-id/dm-name-mpathb --group=ssd_write /dev/disk/by-id/dm-name-mpatha /dev/disk/by-id/dm-name-mpathm --group hdd=/dev/disk/by-id/dm-name-mpathc /dev/disk/by-id/dm-name-mpathd /dev/disk/by-id/dm-name-mpathe /dev/disk/by-id/dm-name-mpathf /dev/disk/by-id/dm-name-mpathg /dev/disk/by-id/dm-name-mpathh /dev/disk/by-id/dm-name-mpathi /dev/disk/by-id/dm-name-mpathj /dev/disk/by-id/dm-name-mpathk /dev/disk/by-id/dm-name-mpathl /dev/disk/by-id/dm-name-mpathn /dev/disk/by-id/dm-name-mpatho /dev/disk/by-id/dm-name-mpathp /dev/disk/by-id/dm-name-mpathq /dev/disk/by-id/dm-name-mpathr /dev/disk/by-id/dm-name-mpaths /dev/disk/by-id/dm-name-mpatht /dev/disk/by-id/dm-name-mpathu --erasure_code --replicas=2 --foreground_target=ssd_write --promote_target=ssd_read --background_target=hdd
Starting program: /usr/local/sbin/bcachefs format --group=ssd_read /dev/disk/by-id/dm-name-mpathb --group=ssd_write /dev/disk/by-id/dm-name-mpatha /dev/disk/by-id/dm-name-mpathm --group hdd=/dev/disk/by-id/dm-name-mpathc /dev/disk/by-id/dm-name-mpathd /dev/disk/by-id/dm-name-mpathe /dev/disk/by-id/dm-name-mpathf /dev/disk/by-id/dm-name-mpathg /dev/disk/by-id/dm-name-mpathh /dev/disk/by-id/dm-name-mpathi /dev/disk/by-id/dm-name-mpathj /dev/disk/by-id/dm-name-mpathk /dev/disk/by-id/dm-name-mpathl /dev/disk/by-id/dm-name-mpathn /dev/disk/by-id/dm-name-mpatho /dev/disk/by-id/dm-name-mpathp /dev/disk/by-id/dm-name-mpathq /dev/disk/by-id/dm-name-mpathr /dev/disk/by-id/dm-name-mpaths /dev/disk/by-id/dm-name-mpatht /dev/disk/by-id/dm-name-mpathu --erasure_code --replicas=2 --foreground_target=ssd_write --promote_target=ssd_read --background_target=hdd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff766b700 (LWP 2894)]
[New Thread 0x7ffff7662700 (LWP 2895)]
[New Thread 0x7ffff7659700 (LWP 2896)]
[New Thread 0x7ffff7650700 (LWP 2897)]
[New Thread 0x7ffff7647700 (LWP 2898)]
[New Thread 0x7ffff763e700 (LWP 2899)]
[New Thread 0x7ffff7635700 (LWP 2900)]

Thread 1 "bcachefs" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:96
96      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) 
(gdb) backtrace
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:96
#1  0x00007ffff76c99ef in _IO_vfprintf_internal (s=0x7fffffffb9c0, format=0x55555563b29f "error creating disk path: %s", ap=0x7fffffffe088) at vfprintf.c:1638
#2  0x00007ffff76ca866 in buffered_vfprintf (s=s@entry=0x7ffff7834680 <_IO_2_1_stderr_>, format=format@entry=0x55555563b29f "error creating disk path: %s", args=args@entry=0x7fffffffe088) at vfprintf.c:2322
#3  0x00007ffff76c7eb2 in _IO_vfprintf_internal (s=0x7ffff7834680 <_IO_2_1_stderr_>, format=format@entry=0x55555563b29f "error creating disk path: %s", ap=ap@entry=0x7fffffffe088) at vfprintf.c:1296
#4  0x0000555555571266 in die (fmt=fmt@entry=0x55555563b29f "error creating disk path: %s") at tools-util.c:30
#5  0x00005555556061e3 in bch2_format (fs_opt_strs=..., fs_opts=..., opts=..., devs=devs@entry=0x55555575d5b0, nr_devs=nr_devs@entry=20) at libbcachefs.c:260
#6  0x0000555555604737 in cmd_format (argc=<optimized out>, argv=<optimized out>) at cmd_format.c:234
#7  0x000055555555bec4 in main (argc=<optimized out>, argv=0x7fffffffe8c8) at bcachefs.c:166
(gdb)
```

**Comment by koverstreet** [comment]
Thanks, that was what I needed! Fixed.
